### ISSUE TITLE
[Performance Issue] Extreme lag when moving the camera

### ISSUE THREAD

**Issue by HoneybeeSorceress** [TerrariaCraft/Issues#109]
I recently installed TerrariaCraft using the launcher provided on the website. Upon generating my world, on any size, I experience an extreme amount of frame loss(single digits) when turning to face in any direction. Any advice on remedying this issue is appreciated.

Things I have tried to increase performance.
- Allocating more ram to the game.
- Changing the performance settings packaged with install.
- Lowering Rendering distance all the way.
- Uninstalling and reinstalling.
- Generating a world with different settings.
- Installing Optifine.

My system specs are
- Windows 10 64bit
- Intel(R) Xeon(R) CPU E5-2667 v3 3.20 ghz (8 cpus)
- 12gb ram
- Nvidia Quadro P5000
- Vram 16gb

**Comment by Zeitheron** [comment]
What is your render distance? It is recommended to run 8x6 render distance.
Also not sure about your CPU.

**Comment by HoneybeeSorceress** [comment]
Ah right I forgot to mention that. it started off at 8x6. Problem persists at on the lowest settings.

**Comment by Zeitheron** [comment]
I have quickly checked your CPU against our recommended CPU (R5 2600) and it does seem to lack behind in supported memory frequencies, which in turn lowers bandwidth, which might cause your game to stutter due to Java's garbage collector taking a long time. You might want to see other garbage collectors, that could help you slightly stabilize your performance, but you will likely still experience problems.

**Comment by HoneybeeSorceress** [comment]
Ah that's a shame. Thanks for the help.

**Comment by Zeitheron** [comment]
Sorry! The mod is quite intensive due to it using Minecraft as a core, which is not optimized.
My best offer would be updating ColoredLux as it reduced some memory problems internally in the last build. If that still doesn't help, you may try to remove ColoredLux, but then again, it won't fully save you from these problems.
