### ISSUE TITLE
Inventory 

### ISSUE THREAD

**Issue by L0g4n2002** [TerrariaCraft/Issues#120]
**WARNING!**
You must fill out the following information in order to receive any help.
Leaving things "as-is" does not provide us with any useful information.
This warning may be deleted.

**Describe the bug**
the more itens you have, slower the inventory menu becomes, when opening chests, takes minutes to move the cursor

**To Reproduce**
1. open inventory
2. See error

**Expected behavior**
not to drop fps opening the inventory

**Screenshots**

**Mod Versions (please complete the following information):**
 - Minecraft Forge: [8.0.99.99]
 - HammerLib (HammerCore) [12.2.50]
 - TerrariaCraft [12.6.2]
 - MusicLayer [12.2.22]
 - OpenCubicChunks [0.0.1208..0]
 - ColoredLux [12.6.33]
 - Optifine Installed: [no] (Only required for visual debugging)
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: Intel Xeon E5 2666 v3
 - GPU: NVIDIA GeForce GTX 1060 3GB
 - RAM: 16GB  2113Mhz
 - Java: 8.0.3810.9

**Additional context**
loving this mod!

**Comment by Zeitheron** [comment]
This is an issue that has already been adressed in idev builds using some caching trickery.

**Comment by Gorantev** [comment]
It exists on current "stable" (12.6.2) build (dropping FPS from decent double-digit numbers all the way down to 1-12 FPS in Creative), but I will patiently wait until the next stable build releases (where this issue is already resolved). For now, I'll just have to put up with it, it seems, while I test some other "edge cases".

And while I am here, a suggestion for release schedule tweaks - it is probably a good idea to release performance-improving and bug fixing updates "separately" from the main schedule, to make the experience better while people playing on stable builds wait for the next major release. Not that said change would necessarily be implemented, but it would have been nice. Although it might be too much to ask from just one man...

**Comment by Zeitheron** [comment]
I do not have multiple branches nor I  have the time to merge conflicts between branches to address fixes that use refactors and such, sorry. The mod will not get "patch" builds after the build becomes more-less stable. It is what it is.
