### ISSUE TITLE
Three bugs

### ISSUE THREAD

**Issue by michieo** [TerrariaCraft/Issues#32]
Bug 1.
If you have multiple spawn eggs and you try to swap one with a different type it will turn the one you are holding into the one you try to swap it with and stack it. 

Bug 2.
With spelunker potion when you break the ores the ore stays there for a second after its already been destroyed (its still destroyed its just visual)

Bug 3. 
When making a new world your vanity stays from your other worlds

**Comment by Zeitheron** [comment]
First one is not really a bug. We do not care about NBT tags of items since in Terraria stack's additional information (like gel color) does not affect the item itself and is still combinable.
We will replace spawn eggs with critter-like items that place enemies properly.

Second issue is a little more problematic since it requires listening to block break events and rebaking render map for all ores spelunker effect is rendering. We'll see about that, but it is not critical, it's just visual.

As for the last one, will have to inspect why that might be happening, since that is not normal behavior and should not occur.
