### ISSUE TITLE
[SUGGESTION] Change font to Andy Bold

### ISSUE THREAD

**Issue by fn2006** [TerrariaCraft/Issues#62]
Right now the mod is using the default Mojangles font, I think it looks out of place compared to the rest of the UI and that you should change it to [Andy Bold](https://www.ffonts.net/Andy-Bold.font), the font used by Terraria.

**Comment by Zeitheron** [comment]
This is not happening due to the fact that the font doesn't support other languages besides just English, which is sad.
You can use third-party mods to apply the font, but it's not something we'll spend our time on at this point.
(Unless there will be an update to the font to support more characters)
