### ISSUE TITLE
[BUG] slow mining after after attacking/killing

### ISSUE THREAD

**Issue by infernalgamer0** [TerrariaCraft/Issues#72]
Whenever you attack or kill something it will result in your mining being slowed down.

**To Reproduce**
1. attack/kill something
2. See error

**Expected behavior**
I expected my mining to stay the same speed after attacking something.

**Screenshots**

**Mod Versions (please complete the following information):**
 - Minecraft Forge: [e.g. 14.23.5.2847]
 - HammerLib (HammerCore) [e.g. 2.0.6.19]
 - TerrariaCraft [e.g. 12.2.17]
 - MusicLayer [e.g. 12.2.20]
 - OpenCubicChunks [e.g. 0.0.1055.0]
 - (if installed) ColoredLux [e.g. 12.3.17]
 - (if installed) Corsair McCUE [e.g. 12.2.5]
 - Optifine Installed: [no] (Only required for visual debugging)
 
 **Hardware & Software info (Might be important in some cases)**
 - CPU: [e.g. AMD Ryzen 9 3900x] (lookup in task manager)
 - GPU: [e.g. NVIDIA GeForce RTX 2070 SUPER] (lookup in task manager)
 - RAM: [e.g. 64 GBs @ 3000 MHz] (lookup in task manager)
 - Java: [e.g. Java 8 Update 231 (64-bit)] (lookup in apps)

**Additional context**
I was using a spear as my weapon and a golden pickaxe if that helps.

**Comment by Puckuchu** [comment]
I don't know if this is connected to killing an enemy. I was having the issue while simply breaking blocks on the surface. the bug didn't occur underground.

Every time it happened however, it seemed that the swing sound effect was doubled over. like each time the pick was trying to interact with multiple things at once.
While I was breaking Grass Blocks, I thought it was because plants always have a chance to grow on grass blocks, ironed that one out quickly after I have built a wood floor and things on-top of it still had trouble breaking with that overlapping swing sound.
I then thought it could be connected to buffs inflicted on the player such as that from Campfires and Heartlamps. that could be connected to it but I doubt it.
My final conclusion was that it might be a framerate thing, but that wouldn't answer why it only happens in that one area near where I built my house. I had a Consistent framerate always. Locking it at 80FPS from within the settings menu.

The Pick is trying to hit something else while mining the block, that's all I can determine while I was playing.

**Comment by Puckuchu** [comment]
> I don't know if this is connected to killing an enemy. I was having the issue while simply breaking blocks on the surface. the bug didn't occur underground.
> 
> Every time it happened however, it seemed that the swing sound effect was doubled over. like each time the pick was trying to interact with multiple things at once. While I was breaking Grass Blocks, I thought it was because plants always have a chance to grow on grass blocks, ironed that one out quickly after I have built a wood floor and things on-top of it still had trouble breaking with that overlapping swing sound. I then thought it could be connected to buffs inflicted on the player such as that from Campfires and Heartlamps. that could be connected to it but I doubt it. My final conclusion was that it might be a framerate thing, but that wouldn't answer why it only happens in that one area near where I built my house. I had a Consistent framerate always. Locking it at 80FPS from within the settings menu.
> 
> The Pick is trying to hit something else while mining the block, that's all I can determine while I was playing.

I figured it out. when standing near entities, This includes the gore on the ground, the Pick is attempting to hit the entities at the same time as mining, causing the actual process of mining a block less and less consistent the more entities there are. Gore takes time to disappear even when it's fully invisible. meaning that the gore still lingers after it's gone, making it easy to mistake that Killing something is the cause of the issue.
similarly, what was causing this in my house is the NPC's within it, and before that the Squirrels and Bunnies. One cannot hit NPC's anyway, so NPC's within houses is just something I'll have to put up with for now.

I'm currently using Terraria Craft 12.5.32

**Comment by Zeitheron** [comment]
Fixed.
